### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Eason90** [zhangyuChen1991/OverWatchLoading#3]
flush() -> hexagons[0].addScale();

**Comment by zhangyuChen1991** [comment]
空指针已修复。(私聊的那个问题还没解决，我在摄像页面引用loading，并没有引起重复调用onMeasure()，应该是和具体的布局有关。头疼中...)

**Comment by newIDforLOL** [comment]
按生存周期的话，onMeasure结束才能getMeasuredWidth和getMeasuredHeight，我猜是这部分导致的问题……我在Fragment中调用了阁下的屁股loading也出现了空指针，调整了onMeasure这里才正常。

不过还是感谢阁下的代码～
