### ISSUE TITLE
为什么在onCreate中直接startAnim无法开始动画呢

### ISSUE THREAD

**Issue by zofnk** [zhangyuChen1991/OverWatchLoading#6]
只能在监听事件中触发startAnim or stopAnim 才有效

**Comment by zhangyuChen1991** [comment]
因为要测量View尺寸，计算初始数据。onCreate里尺寸没计算出来，所以不会开启动画。你可以在页面获得焦点时调用startAnim ，或者在自定义View里重写onFinishInflate()方法，在里面启动动画。PS：看来是应该添加一个自动开启动画的接口~

**Comment by zofnk** [comment]
@Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        startAnim();
        Log.e(TAG, "onFinishInflate: " + startAnim());
    }
Log ; E/OWLoadingView: onFinishInflate: false

新手表示有点懵逼

**Comment by zhangyuChen1991** [comment]
我这基础也是不牢。。onFinishInflate()在onMeasure()前就给执行了
你要不在Activity里的onWindowFocusChanged()里调吧
`  
 @Override
    public void onWindowFocusChanged(boolean hasWindowFocus) {
        super.onWindowFocusChanged(hasWindowFocus);
        if(hasWindowFocus){//获得焦点，开始动画
            owLoadingView.startAnim();
        }else{//失去焦点，中止动画
            owLoadingView.stopAnim();
        }
    }
`
这样的话来回切的时候不知道会不会出什么问题。这个view的生命周期没处理好，有待改进呐！

**Comment by zofnk** [comment]
这样可以是可以...
不过需求是进来显示Loading..
然后请求onSuccess回调的时候stopAnim
我再试试!谢谢了!
ps:还是想要一个自动开启动画的接口~

**Comment by zhangyuChen1991** [comment]
我加了自动开启的接口，其实也是在onWindowFocusChanged()里处理的。不stopAnim()的话在后台不可见时它也会运行，所以建议不必要用的时候及时关掉。

**Comment by zofnk** [comment]
看到更新的代码了..谢谢!
